events { worker_connections 1024; }

http {
    upstream gateway {
        server order-gateway:3000;
    }

    upstream identity {
        server identity-provider:3000;
    }

    upstream client_ui {
        server client-ui:80;
    }

    upstream notification_hub {
        server notification-hub:3000;
    }

    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://identity/;
        }

        location /api/order/ {
            proxy_pass http://gateway/;
        }

        location /socket.io/ {
            proxy_pass http://notification_hub/socket.io/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://client_ui/;
        }
    }
}
